services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - data:/data

volumes:
  data:

networks:
  default:
    external: true
    name: base
